name: 'Github JD-sign bot'

on:
  #push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '5 16 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Run app
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        PUSH_KEY: ${{ secrets.SCKEY }}
      run: |
        cd jd_sign_bot
        npm install
        node app.js
      